// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4bnUcjOIbDtRCBa94QjxchBjBdgTRMls',
    appId: '1:454619571339:web:c3c3b234cb168c9e41e08e',
    messagingSenderId: '454619571339',
    projectId: 'kpr-sports',
    authDomain: 'kpr-sports.firebaseapp.com',
    storageBucket: 'kpr-sports.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA95mXPSrYRUV5fTb1FzhrG6P5SInuZF40',
    appId: '1:454619571339:android:ba93667fbd2becf341e08e',
    messagingSenderId: '454619571339',
    projectId: 'kpr-sports',
    storageBucket: 'kpr-sports.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgNDuXz5NVJQCXs1V-Gtv3Z2XWnpjx0Zs',
    appId: '1:454619571339:ios:7d8e65b60001008141e08e',
    messagingSenderId: '454619571339',
    projectId: 'kpr-sports',
    storageBucket: 'kpr-sports.appspot.com',
    iosClientId: '454619571339-95g6nl8gkfkntdiuknucfj8t1qgg3p1t.apps.googleusercontent.com',
    iosBundleId: 'com.kprsports.kprSports',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgNDuXz5NVJQCXs1V-Gtv3Z2XWnpjx0Zs',
    appId: '1:454619571339:ios:7d8e65b60001008141e08e',
    messagingSenderId: '454619571339',
    projectId: 'kpr-sports',
    storageBucket: 'kpr-sports.appspot.com',
    iosClientId: '454619571339-95g6nl8gkfkntdiuknucfj8t1qgg3p1t.apps.googleusercontent.com',
    iosBundleId: 'com.kprsports.kprSports',
  );
}
